---
name: Jim
surname: Junker
position: "Ecologist"
address: "Louisiana Universities Marine Consortium"
phone: +1 651 587 1477
www: jimjunker.com
email: "james.junker1@gmail.com"
twitter: jimjunker
github: jimjunker1
date: "`r format(Sys.time(), '%B %Y')`"
headcolor:
output:
  # vitae::awesomecv:
  # vitae::hyndman:
  # vitae::moderncv:
  vitae::twentyseconds:
      keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(vitae)
library(RefManageR)
library(rorcid)
library(scholar)
'%ni%' <- Negate('%in%')
```

# Education

```{r}
# edu <- do.call("rbind", rorcid::orcid_educations("0000-0001-9713-2330")$`0000-0001-9713-2330`$`affiliation-group`$summaries)

edu <- readRDS(file = "./data/edu.rds")
edu %>%
  detailed_entries(
    what = `education-summary.role-title`,
    when = `education-summary.end-date.year.value`,
    with = `education-summary.organization.name`,
    where = paste0(`education-summary.organization.address.city`,", ",`education-summary.organization.address.region`)
  )

```


# Publications

```{r, include = TRUE, echo = FALSE}

pubs <- readRDS(file = "./data/pubs.rds") %>% mutate(author = gsub("\\.","", author),
                                                     author = enc2native(author),
                                                     author = gsub(fixed("<ed>"), "i", author, useBytes = TRUE))#;pubs[,'author']
in_review <- data.frame(
  title = c("Resource supply govers the apparent temperature dependence of animal production at multiple timescales","Patterns and drivers of organic matter storage and stoichiometry across a wide stream temperature gradient"),
  author = rep("James R Junker, Wyatt F Cross, Jonathan P Benstead, Alexander D Huryn, James M Hood, Daniel Nelson, Gisli M Gíslason, Jón S Ólafsson",2), journal = c("Ecology Letters","Ecosystems"), 
  year = rep("In Review",2), stringsAsFactors = FALSE)

pubs <- bind_rows(in_review, pubs %>% mutate(year = as.character(year)))

pubs %>%
 detailed_entries(
   what = title,
   when = year,
   with = author,
   where = journal
 )
```

